### ISSUE TITLE
pnpm dev:chrome error

### ISSUE THREAD

**Issue by igoralentyev** [mubaidr/vite-vue3-chrome-extension#79]
Node 20 and 21

```
error when starting dev server:
Error: Missing "./macros" specifier in "vue" package
    at e (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:25)
    at n (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:627)
    at o (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46568:1297)
    at resolveExportsOrImports (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47189:18)
    at resolveDeepImport (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:47212:25)
    at tryNodeResolve (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46977:16)
    at ResolveIdContext.resolveId (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:46727:19)
    at PluginContainer.resolveId (file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:49506:17)
    at async file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66561:15
    at async file:///home/usename/projectname/browser-new/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:50411:14
```

**Comment by mubaidr** [comment]
More information: https://github.com/vuejs/core/issues/6064 and https://github.com/vitejs/vite/issues/15484

Looks like we need to migrate `eslint` or downgrade `vue` version to ~3.3

*vue does not include macros now, as not required.

**Comment by mubaidr** [comment]
Fixed in: https://github.com/mubaidr/vite-vue3-chrome-extension-v3/commit/5ae3285528cc121350a6b83becc66c9e170557d4
